name: compile assets

on:
  workflow_call:
    inputs:
      node:
        default: "16"
        type: string
      cmd:
        default: "production"
        type: string

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node }}

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile assets
        run: npm run ${{ inputs.cmd }}

      - name: Commit compiled files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Compile Assets
          file_pattern: public/
